### ISSUE TITLE
Too strict lower bound on optparse-applicative

### ISSUE THREAD

**Issue by sternenseemann** [kokobd/cabal-hoogle#2]
Can also be built with 0.16.* which is Stackage LTS 19 atm.

**Comment by kokobd** [comment]
@sternenseemann Could you share the use case? The tool is intended to work with cabal, not stack.

**Comment by sternenseemann** [comment]
I want to compile cabal-hoogle using optparse-applicative 0.16 which we ship in nixpkgs.

**Comment by kokobd** [comment]
Done. Updated the version bound both in master and hackage.
